# Generated by Django 5.0.8 on 2024-08-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='header_pic',
        ),
    ]
