# Generated by Django 5.0.8 on 2024-10-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avi_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avi_pic',
            field=models.ImageField(default=None, upload_to='avi/'),
        ),
    ]
