# Generated by Django 5.0.8 on 2024-10-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_avi_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avi_pic',
            field=models.ImageField(blank=True, default='media/default_avi.jpg', null=True, upload_to='avi/'),
        ),
    ]
