# Generated by Django 5.1.3 on 2025-02-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_avi_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avi_pic',
            field=models.ImageField(blank=True, default='avi/default_avi.jpg', null=True, upload_to='avi/'),
        ),
    ]
