# Generated by Django 5.0.8 on 2024-09-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlisttracks',
            name='preview_url',
            field=models.CharField(default=''),
        ),
    ]
