# Generated by Django 5.1.3 on 2025-03-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_playlist_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlisttracks',
            name='track_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
