# Generated by Django 5.0.8 on 2024-10-04 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_playlisttracks_preview_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaylistHashtags',
        ),
    ]
