# Generated by Django 5.1.3 on 2024-12-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_delete_playlisthashtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, default='', max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/playlist/'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_description',
            field=models.CharField(blank=True, default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='playlist',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='feed.hashtag'),
        ),
    ]
