# Generated by Django 5.1.3 on 2024-12-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_hashtag_playlist_image_playlist_playlist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_description',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
