# Generated by Django 5.1.3 on 2025-01-02 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_playlist_playlist_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='image',
        ),
    ]
